<?php
/**
 * * @file
 * Code for dsgf module
 */
function dsgf_theme(){
  $theme['hello_page']=[
    'variables' => ['message' => NULL,'from' => NULL, 'to'=>NULL, 'name'=>NULL, 'mytitle'=>NULL,'email'=>NULL,'demoservice'=>NULL],
    'template' => 'hello_page',
  ];
  $theme['hello_block']=[
    'variables' => ['message' => NULL],
    'template' => 'hello_block',
  ];
  return $theme;
}